import thinky from '../thinky';

const type = thinky.type;

const History = thinky.createModel('History', {
    // Optional => not specified in bodies but generated by RethinkDB
    id         : type.string().optional(),
    points     : [ type.number() ],
    createdAt  : type.date().default(new Date()),
    editedAt   : Date,
    isRemoved  : type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

History.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

History.ensureIndex('createdAt');
History.ensureIndex('editedAt');

History.associate = models => {
    models.History.hasAndBelongsToMany(models.User, 'users', 'id', 'userId');
};

export default History;
