import thinky from '../thinky';

const type = thinky.type;

const User = thinky.createModel('User', {
    // Optional => not specified in bodies but generated by RethinkDB
    id         : type.string().optional(),
    pseudo     : String,
    password   : String,
    email      : String,
    bio        : String,
    lastLogin  : Date,
    createdAt  : type.date().default(new Date()),
    editedAt   : Date,
    isRemoved  : type.boolean().default(false)
}, {
    enforce_missing: true,
    enforce_extra  : 'remove',
    enforce_type   : 'strict'
});

User.pre('save', function (next) {
    this.editedAt = new Date();
    next();
});

User.ensureIndex('pseudo');
User.ensureIndex('email');
User.ensureIndex('bio');
User.ensureIndex('lastLogin');
User.ensureIndex('createdAt');
User.ensureIndex('editedAt');

User.associate = models => {

};

export default User;
